export const entities = {
  results: [
    {
      _id: "1",
      productImage: "/assets/products/almarai-milk.jpg",
      productName: "Milk",
      variantName: "1 Litre",
      brand: "Almarai",
      category: "Dairy",
      locations: "All Locations",
      sku: "101020209293",
      unit: "Per Litre",
      price: "18",
      productStatus: "active",
    },
    {
      _id: "2",
      productImage: "/assets/products/vanilla-cake.png",
      productName: "Vanilla Cake Bar",
      variantName: "500 ml",
      brand: "7Days",
      category: "Bakery",
      locations: "T-Mart Riyadh",
      sku: "103323211293",
      unit: "Per Litre",
      price: "50",
      productStatus: "inactive",
    },
    {
      _id: "3",
      productImage: "/assets/products/chicken.png",
      productName: "Chicken",
      variantName: "2 Litres",
      brand: "Alyoum",
      category: "Meat",
      locations: "All Locations",
      unit: "Per Litre",
      sku: "172772793293",
      price: "80",
      productStatus: "active",
    },
  ],
};
