export const Screens = {
  companyDetail: "companyDetail",
  vendorTab: "vendorTab",
  deviceTab: "deviceTab",
  variantTabs: "variantTabs",
  poGrn: "poGrn",
  internalTransfer: "internalTransfer",
  rolesAndPermissions: "rolesAndPermissions",
  createLocation: "CreateLocation",
  bilingRightView: "bilingRightView",
  bilingLeftView: "bilingLeftView",
  accountDetails: "accountDetails",
  apkManagement: "apkManagement",
  loginTabs: "loginTabs",
  companiesList: "companiesList",
  customersList: "customersList",
  promotionsList: "promotionsList",
  pos: "pos",
  subscriptions: "subscriptions",
};
